name: Teste

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -V

  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pavi2410/html-preview-action@v2 
        with: 
          html_file: 'homepage.html'

  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado"
